const fs = require('fs');

const filePath = 'i:\\techpro excersice\\aiorisis\\data\\TeacherProfileData.tsx';
let content = fs.readFileSync(filePath, 'utf8');

// Add import if not exists
if (!content.includes('LocalizedText')) {
    content = `import { LocalizedText } from "@/components/extraComponents/HelperTranslate";\n` + content;
}

// Update interface
content = content.replace('shortDescription: string;', 'shortDescription: LocalizedText;');
content = content.replace('fullDescription: string;', 'fullDescription: LocalizedText;');
content = content.replace('categoryType: string;', 'categoryType: LocalizedText;');

// Helper to replace string fields with el/en using translation map
const translations = {
    // Evi
    "Ασχολείται με τον αθλητισμό από πολύ μικρή ηλικία.\\n Έκανε τα πρώτα της βήματα στις εναέριες τέχνες (Aerial Silks) το 2012 και η αγάπη της γι'αυτές την οδήγησε να ασχοληθεί επαγγελματικά και να διδάσκει από το 2020. \\nΕίναι πιστοποιημένη δασκάλα της Aerial Yoga 150hrs, Aerial Yin Yoga 50hrs, Yoga 500 hrs και Prenatal/Postnatal Yoga 50hrs από την Yoga Alliance.": "She has been involved in sports since a very young age.\\n She took her first steps in aerial arts (Aerial Silks) in 2012 and her love for them led her to pursue it professionally and teach since 2020. \\nShe is a certified Aerial Yoga teacher 150hrs, Aerial Yin Yoga 50hrs, Yoga 500 hrs and Prenatal/Postnatal Yoga 50hrs by Yoga Alliance.",
    
    // We will do descriptions by replacing `shortDescription: "..."` and `fullDescription: \`...\`` manually using string replace.
};

// Evi shortDescription
content = content.replace(
    /shortDescription:\s*"Ασχολείται με τον αθλητισμό από πολύ μικρή ηλικία\.[\s\S]*?από την Yoga Alliance\.",/,
    `shortDescription: {\n      el: "Ασχολείται με τον αθλητισμό από πολύ μικρή ηλικία.\\n Έκανε τα πρώτα της βήματα στις εναέριες τέχνες (Aerial Silks) το 2012 και η αγάπη της γι'αυτές την οδήγησε να ασχοληθεί επαγγελματικά και να διδάσκει από το 2020. \\nΕίναι πιστοποιημένη δασκάλα της Aerial Yoga 150hrs, Aerial Yin Yoga 50hrs, Yoga 500 hrs και Prenatal/Postnatal Yoga 50hrs από την Yoga Alliance.",\n      en: "She has been involved in sports since a very young age.\\n She took her first steps in aerial arts (Aerial Silks) in 2012 and her love for them led her to pursue it professionally and teach since 2020. \\nShe is a certified Aerial Yoga teacher 150hrs, Aerial Yin Yoga 50hrs, Yoga 500 hrs and Prenatal/Postnatal Yoga 50hrs by Yoga Alliance."\n    },`
);

// Evi fullDescription
content = content.replace(
    /fullDescription:\s*`\s*<div class="space-y-6">[\s\S]*?<\/ul>\s*<\/div>\s*`,/,
    `fullDescription: {\n      el: \`\n    <div class="space-y-6">\n    <p class="text-lg font-medium text-neutral-800 leading-relaxed">Από πολύ μικρή ηλικία ξεκίνησε να ασχολείται με τον αθλητισμό, χτίζοντας μια γερή βάση σωματικής επίγνωσης.</p>\n    <p class="text-neutral-600">Το 2012 έκανε τα πρώτα της βήματα στις εναέριες τέχνες (Aerial Silks), και η αγάπη της γι’ αυτές την οδήγησε να αφιερωθεί επαγγελματικά και να διδάσκει από το 2020.</p>\n    <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Πιστοποιήσεις Yoga Alliance:</p>\n    <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n      <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga (150 ώρες)</li>\n      <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yin Yoga (50 ώρες)</li>\n      <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Yoga (500 ώρες)</li>\n      <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Prenatal/Postnatal Yoga (50 ώρες)</li>\n    </ul>\n    </div>\n\`, \n      en: \`\n    <div class="space-y-6">\n    <p class="text-lg font-medium text-neutral-800 leading-relaxed">From a very young age she started to engage in sports, building a solid foundation of body awareness.</p>\n    <p class="text-neutral-600">In 2012 she took her first steps in aerial arts (Aerial Silks), and her love for them led her to devote herself professionally and teach since 2020.</p>\n    <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Yoga Alliance Certifications:</p>\n    <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n      <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga (150 hours)</li>\n      <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yin Yoga (50 hours)</li>\n      <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Yoga (500 hours)</li>\n      <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Prenatal/Postnatal Yoga (50 hours)</li>\n    </ul>\n    </div>\n\`\n    },`
);

// All empty shortDescriptions
content = content.replace(
    /shortDescription:\s*"",/g,
    `shortDescription: {\n      el: "",\n      en: ""\n    },`
);

// Rafaela fullDescription
content = content.replace(
    /fullDescription:\s*`[\s\S]*?Πιστοποιημένη yoga instructor \(700hr RYT\)[\s\S]*?<\/div>\n`,/,
    `fullDescription: {\n      el: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Πιστοποιημένη yoga instructor (700hr RYT) από το 2019, με βαθιά προσήλωση στη θεραπευτική δύναμη της κίνησης.</p>\n      <p class="text-neutral-600 leading-relaxed">Το 2021 εξειδικεύτηκε στην Aerial yoga και η αγάπη της για τα παιδιά την οδήγησε στην απόκτηση εξειδίκευσης στην Παιδική Yoga.</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Εξειδικεύσεις & Επιμορφώσεις:</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Prenatal & Postnatal Yoga</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Breathworking & Meditation</li>\n      </ul>\n    </div>\n\`, \n      en: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Certified yoga instructor (700hr RYT) since 2019, with a deep dedication to the healing power of movement.</p>\n      <p class="text-neutral-600 leading-relaxed">In 2021 she specialized in Aerial yoga and her love for children led her to acquire a specialization in Kids Yoga.</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Specializations & Seminars:</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Prenatal & Postnatal Yoga</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Breathworking & Meditation</li>\n      </ul>\n    </div>\n\`\n    },`
);

// Natasa fullDescription
content = content.replace(
    /fullDescription:\s*`[\s\S]*?Πιστοποιημένη δασκάλα της Yoga και μέλος[\s\S]*?<\/div>\n`,/,
    `fullDescription: {\n      el: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Πιστοποιημένη δασκάλα της Yoga και μέλος της Yoga Alliance USA (E-RYT 300h).</p>\n      <p class="text-neutral-600 leading-relaxed italic">"Το ταξίδι γύρω από την φιλοσοφία της Yoga ξεκινάει το 2011, μια αναζήτηση που έγινε τρόπος ζωής."</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Εκπαιδεύσεις & Σεμινάρια:</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Yin Yoga</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Ανατομία & Ευθυγράμμιση</li>\n      </ul>\n    </div>\n\`, \n      en: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Certified Yoga teacher and member of Yoga Alliance USA (E-RYT 300h).</p>\n      <p class="text-neutral-600 leading-relaxed italic">"The journey around the philosophy of Yoga starts in 2011, a quest that became a way of life."</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Trainings & Seminars:</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Yin Yoga</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Anatomy & Alignment</li>\n      </ul>\n    </div>\n\`\n    },`
);

// Marialina fullDescription
content = content.replace(
    /fullDescription:\s*`[\s\S]*?Δραστηριοποιείται στον χώρο του pole dance[\s\S]*?<\/div>\n`,/,
    `fullDescription: {\n      el: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Δραστηριοποιείται στον χώρο του pole dance από το 2013, διδάσκοντας σε όλα τα επίπεδα.</p>\n      <p class="text-neutral-600 leading-relaxed">Τα τελευταία 6 χρόνια προετοιμάζει αθλητές για αγωνιστικό επίπεδο, δίνοντας έμφαση στην ακρίβεια της τεχνικής και την καλλιτεχνική έκφραση.</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Διακρίσεις (2017 - 2022):</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· 1η Θέση - Πανελλήνιος Διαγωνισμός</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· 3η Θέση - Artistic Pole</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· 4η Θέση - Pole Sport</li>\n      </ul>\n    </div>\n\`, \n      en: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Has been active in the field of pole dance since 2013, teaching all levels.</p>\n      <p class="text-neutral-600 leading-relaxed">For the past 6 years she has been preparing athletes for competitive level, emphasizing precision of technique and artistic expression.</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Awards (2017 - 2022):</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· 1st Place - Panhellenic Competition</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· 3rd Place - Artistic Pole</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· 4th Place - Pole Sport</li>\n      </ul>\n    </div>\n\`\n    },`
);

// Natalia fullDescription
content = content.replace(
    /fullDescription:\s*`[\s\S]*?Με αφετηρία το μπαλέτο[\s\S]*?<\/div>\n`,/,
    `fullDescription: {\n      el: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Με αφετηρία το μπαλέτο από την ηλικία των 3 ετών, η Ναταλία εξελίχθηκε στον σύγχρονο και εναέριο χορό.</p>\n      <p class="text-neutral-600 leading-relaxed">Διδάσκει τα τελευταία 9 χρόνια, συνδυάζοντας την πειθαρχία του κλασικού χορού με την ελευθερία του Aerial Hoop.</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Τίτλοι Σπουδών I.S.T.D.:</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· DDE (Diploma in Dance Education)</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Advanced 2 in Modern Theatre</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Contemporary Foundation</li>\n      </ul>\n    </div>\n\`, \n      en: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Starting with ballet from the age of 3, Natalia evolved into contemporary and aerial dance.</p>\n      <p class="text-neutral-600 leading-relaxed">She has been teaching for the past 9 years, combining the discipline of classical dance with the freedom of Aerial Hoop.</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">I.S.T.D. Degrees:</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· DDE (Diploma in Dance Education)</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Advanced 2 in Modern Theatre</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Contemporary Foundation</li>\n      </ul>\n    </div>\n\`\n    },`
);

// Stella fullDescription
content = content.replace(
    /fullDescription:\s*`[\s\S]*?Ασχολείται με τα εναέρια ακροβατικά[\s\S]*?<\/div>\s*`/,
    `fullDescription: {\n      el: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Ασχολείται με τα εναέρια ακροβατικά τα τελευταία δέκα χρόνια, αναζητώντας πάντα την τελειότητα στην κίνηση.</p>\n      <p class="text-neutral-600 leading-relaxed">Μέσα από τη συνεχή προσωπική προπόνηση και σεμινάρια με διεθνείς προπονητές, έχει διαμορφώσει ένα μοναδικό στυλ προσέγγισης της εναέριας τεχνικής.</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Κύρια Ειδίκευση:</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Ακροβατικό Πανί (Silks)</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Ακροβατικό Σχοινί (Rope)</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Εναέρια Τεχνική & Element Understanding</li>\n      </ul>\n    </div>\n    \`,\n      en: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Has been involved in aerial acrobatics for the past ten years, always seeking perfection in movement.</p>\n      <p class="text-neutral-600 leading-relaxed">Through continuous personal training and seminars with international coaches, she has developed a unique style of approaching aerial technique.</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Main Specialization:</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Silks</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Rope</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Technique & Element Understanding</li>\n      </ul>\n    </div>\n    \`\n    }`
);

// Eleni fullDescription
content = content.replace(
    /fullDescription:\s*`[\s\S]*?Εχω μεγαλώσει μέσα από τη κίνηση[\s\S]*?<\/div>\s*`/,
    `fullDescription: {\n      el: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">Εχω μεγαλώσει μέσα από τη κίνηση. Με πολυ αγάπη και σεβασμό στο σώμα, μου αρέσει μέσα από διαφορετικές τεχνικές να ανακαλύπτω που μπορεί να φτάσει το σώμα και πως μπορούν όλα τα είδη να συνδυαστούν.</p>\n      <p class="text-neutral-600 leading-relaxed">Μέσα από το χορό μαθαίνω τη σύνδεση της κάθε κίνησης με την επόμενη και ανακαλύπτω καινούργιους τρόπους να τα συνδεω. Η γιόγκα είναι ένα είδος που με βοηθάει να ακούω το σώμα μου και να νιώθω την κάθε κίνηση. Μου αρέσουν οι ροές στα μαθήματα γιογκας και η βασική μου προτεραιότητα είναι να συνδέσουμε το νου μας με το σώμα μας αφήνοντας όλες τις σκέψεις έξω από την αίθουσα.</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Κύρια Ειδίκευση:</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga Kids</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga Teens</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Vinyasa Flow Yoga</li>\n      </ul>\n    </div>\n    \`,\n      en: \`\n    <div class="space-y-6">\n      <p class="text-lg font-medium text-neutral-800 leading-relaxed">I grew up through movement. With much love and respect for the body, I like through different techniques to discover where the body can reach and how all types can be combined.</p>\n      <p class="text-neutral-600 leading-relaxed">Through dance I learn the connection of each movement with the next and I discover new ways to connect them. Yoga is a genre that helps me listen to my body and feel every movement. I like the flows in yoga classes and my main priority is to connect our mind with our body leaving all thoughts outside the room.</p>\n      <p class="text-[#B9007C] font-bold uppercase tracking-wider text-sm">Main Specialization:</p>\n      <ul class="grid grid-cols-1 sm:grid-cols-2 gap-3 list-none !pl-0">\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga Kids</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Aerial Yoga Teens</li>\n        <li class="bg-[#F6F1EB] p-3 rounded-xl border border-[#B9007C]/10 text-sm">· Vinyasa Flow Yoga</li>\n      </ul>\n    </div>\n    \`\n    }`
);

// categoryType
content = content.replace(/categoryType:\s*"Owner",/g, 'categoryType: { el: "Owner", en: "Owner" },');
content = content.replace(/categoryType:\s*"Instructor",/g, 'categoryType: { el: "Instructor", en: "Instructor" },');

fs.writeFileSync(filePath, content, 'utf8');
console.log('TeacherProfileData.tsx updated');
